# -*- coding: utf-8 -*-
"""TALLER_18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUVz4_JrozFgACOgWuT2ln60CeVDrkp9
"""

import numpy as np
import math
import matplotlib.pyplot as plt

def regresion_lineal_a0_a1(x, y):
    n = len(x)

    logaritmon_y = [math.log(y_i) for y_i in y]

    potencia2_x = [x_i**2 for x_i in x]

    producto_xy = [x_i * logaritmon_y[i] for i, x_i in enumerate(x)]


    sum_x = sum(x)
    sum_y = sum(logaritmon_y)
    sum_xy = sum(producto_xy)
    sum_x_squared = sum(potencia2_x)

    a1 = (n * sum_xy - sum_x * sum_y) / (n * sum_x_squared - sum_x**2)
    a0 = (sum_y - a1 * sum_x) / n

    return a0, a1

x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [9, 7, 8, 5, 6, 4.5, 4, 2.5]

a0, a1 = regresion_lineal_a0_a1(x, y)
print("La recta de regresión es: y =", a0, "*", "e^(", a1, "x)")


plt.scatter(x, y, label='Datos')
plt.plot(x, [math.exp(a0) * math.exp(a1 * x_i) for x_i in x], color='red', label='Recta de regresión')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()