# -*- coding: utf-8 -*-
"""TALLER_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13pR_my2PUdFkhfrRjZIwX0UWxbai1S4-

#TALLER 7
ERRORES DE REDONDEO
"""

import math

def aprox1(x, n):
    suma = 1
    term = 1
    for i in range(1, n+1):
        term *= -x / i
        suma += term
    return suma

def aprox2(x, n):
    suma = 1
    term = 1
    for i in range(1, n+1):
        term *= x / i
        suma += term
    return 1 / suma

def errorela(aprox, v):
    min_v = 0.0000001
    return abs((aprox - v) / max(abs(v), min_v)) * 100

x = 0.75
v = math.exp(-x)

n = 1
e = 1
esror=0.5*(10**(-8))
while e >= esror:
    aprox = aprox1(x, n)
    e = errorela(aprox, v)
    n += 1

print("Aproximación 1:")
print("Valor: ", str(round(aprox, 8)))
print("Error relativo porcentual: ", str(round(e, 10)))
print("Número de iteraciones:", n-1)

n = 1
e = 1
while e >= esror:
    aprox = aprox2(x, n)
    e = errorela(aprox, v)
    n += 1
print("\nAproximación 2:")
print("Valor: ", str(round(aprox, 8)))
print("Error relativo porcentual: ", str(round(e, 10)))
print("Número de iteraciones:", n-1)